### ISSUE TITLE
cant compile main.py

### ISSUE THREAD

**Issue by svenikea** [RichusX/thinkmorse#1]
I downloaded your mod load ec_sys module with write support but when i compile it it return this error ``Traceback (most recent call last):
  File "main.py", line 63, in <module>
    led(False)
  File "main.py", line 59, in led
    led.flush()
IOError: [Errno 22] Invalid argument
``
maybe my t440s didnt work or there something weird about the mod

**Comment by theritvars** [comment]
Are you running it with Python 3?

**Comment by svenikea** [comment]
I ran in both python2 and 3 and the result is the same

**Comment by theritvars** [comment]
Hmm. Are you running it with sudo and you're absolutely sure you have write support enabled?

**Comment by svenikea** [comment]
I ran it without sudo it said permission denied later with sudo same error on top of this issue. I running Manjaro btw this project is pretty cool so I really into this

**Comment by theritvars** [comment]
I'm running this on Manjaro as well. Could you please paste in the `GRUB_CMDLINE_LINUX_DEFAULT` line of your `/boot/grub/grub.cfg`
