### ISSUE TITLE
Bug?  sleep() for inner element gap.

### ISSUE THREAD

**Issue by contrains** [RichusX/thinkmorse#3]
On lines 71, 79, and 83, should these conditionals be 'and' instead of 'or'?

As an 'or', the conditional is only False overall if the character is both a space and a stroke at the same time, whereas as an 'and', it is only True if it is neither a space nor a stroke, which I believe is what you want.

In formal logic, these two statements are identical: (~A v ~B) = ~(A ^ B).

This comment is in reference to commit 210c350d00a723234e93765065dd8baef1c14bb9.

**Comment by contrains** [comment]
P.S. Great idea for a project!  I plan to try it out when I buy my new ThinkPad.

**Comment by theritvars** [comment]
I believe you are correct. Good catch.
